### ISSUE TITLE
Add Build and Run Instructions for Toshi

### ISSUE THREAD

**Issue by violenil** [mfkd/toshi#1]
Hi, thanks for sharing this amazing book searching tool! I noticed that the repository currently lacks instructions for building the Go code and running the tool on different operating systems. It would be helpful if you could add a section to the README or a separate file with the following details:
	1.	Build Instructions:
	•	Steps to install required dependencies.
	•	Commands to build the Go code for different operating systems (e.g., Linux, macOS, Windows).
	2.	Run Instructions:
	•	How to run the tool once built, including example commands and expected usage.
	•	Any configurations or environment variables needed to get started.

Having these details would make it easier for users to get started and contribute to the project.

Thanks in advance! 😊

**Comment by mfkd** [comment]
I added Installation and usage instructions to the README. Thanks for your feedback!
